### ISSUE TITLE
Please add MeteoSwiss as "owner" on pypi

### ISSUE THREAD

**Issue by fpavogt** [tch521/python-TAMER#2]
Hey @tch521,

We're starting to organize a bit all the MCH Python codes released on pypi. Doing so involves having all the MCH codes owned by the [MeteoSwiss](https://pypi.org/user/MeteoSwiss/) account that has been created on there.

Since this code was released on pypi, could you please log on there, navigate to the code's setting page, and add "MeteoSwiss" as an owner ? 

In addition, I'll note that there this [Github Action](https://github.com/MeteoSwiss/ampycloud/blob/develop/.github/workflows/CI_pypi.yml) can be used to automate the release of your code to pypi. If you feel so enclined, you can add this Actions to your repo, and the code will be pushed to pypi automatically each time a new release is created on Github.

**Comment by tch521** [comment]
Hi @fpavogt, no problem!

**Comment by fpavogt** [comment]
Brilliant ! You're now the "maintainer" of the code on pypi, which means that you'll be able to push new releases as before.

Thanks for the prompt action !
